# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IGZ_NJBHCsIBP-eC350idkVe6k_vb2s2
"""

import numpy as np

array_1d=np.array([1,2,4,5,6,8])

array_2d=np.array([[1,2,4],[5,6,8]])

q_array=np.sum(array_1d)

oq_array=np.mean(array_1d)

k_array=np.prod(array_1d)

print("1D Massiv: ", array_1d)

print("2D Massiv:\n", array_2d)

print("Massivlar yig'indisi: ", q_array)

print("O'rtacha: ", oq_array)

print("Ko'paytma: ", k_array)